"""Turn the scraped loot into the addon's data file.

Only ids and sources go into the addon. Names, icons, stats and tooltips
all come from the client at runtime through C_Item, which keeps the file
small, keeps it correct when Blizzard retunes something, and means we are
not shipping a copy of somebody else's database.

    python WickSuite/tools/emit-gear-data.py

Writes Data.lua into the WicksGear addon folder.
"""
import io
import json
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, "..", "data", "forever"))
ADDON = ("C:/Program Files (x86)/World of Warcraft/_classic_beta_"
         "/Interface/AddOns/WicksGear")


def lua_str(s):
    return '"%s"' % str(s).replace("\\", "\\\\").replace('"', '\\"')


# Wowhead's slot numbers, which are inventory types. The dungeon scrape
# gives slot names directly; the crafted and quest listviews give these.
SLOT_NAME = {
    1: "Head", 2: "Neck", 3: "Shoulder", 4: "Shirt", 5: "Chest", 6: "Waist",
    7: "Legs", 8: "Feet", 9: "Wrist", 10: "Hands", 11: "Finger", 12: "Trinket",
    13: "One-Hand", 14: "Shield", 15: "Ranged", 16: "Back", 17: "Two-Hand",
    19: "Tabard", 20: "Chest", 21: "Main Hand", 22: "Off Hand",
    23: "Held in Off-hand", 25: "Thrown", 26: "Ranged", 28: "Relic",
}
QUALITY_NAME = { 0: "poor", 1: "common", 2: "uncommon", 3: "rare",
                 4: "epic", 5: "legendary" }


def entry_line(it, set_of, extra=""):
    """One table row, from a crafted or quest listview record.

    A quest reward calls the item id `id`; a crafted recipe calls it
    `item`, because from the recipe's point of view the id belongs to the
    thing it makes rather than to itself.
    """
    iid = it.get("id") or it.get("item")
    bits = []
    slot = SLOT_NAME.get(it.get("slotId"))
    if slot:
        bits.append("slot = " + lua_str(slot))
    if isinstance(it.get("ilvl"), int):
        bits.append("ilvl = %d" % it["ilvl"])
    if isinstance(it.get("reqLevel"), int) and it["reqLevel"]:
        bits.append("req = %d" % it["reqLevel"])
    if isinstance(it.get("cls"), int):
        bits.append("cls = %d" % it["cls"])
    if isinstance(it.get("sub"), int):
        bits.append("sub = %d" % it["sub"])
    setname = set_of.get(str(iid))
    if setname:
        bits.append("set = " + lua_str(setname))
    q = it.get("quality")
    qn = QUALITY_NAME.get(q if isinstance(q, int) else -1)
    if qn:
        bits.append("q = " + lua_str(qn))
    if extra:
        bits.append(extra)
    return "        { id = %d, name = %s%s }," % (
        iid, lua_str(it.get("name") or ""),
        (", " + ", ".join(bits)) if bits else "")


def emit_table(path, header, varname, groups, set_of, extra_for=None):
    out = list(header)
    out.append("%s = {" % varname)
    order = []
    for group in sorted(groups):
        rows = groups[group]
        if not rows:
            continue
        order.append(group)
        out.append("    [%s] = {" % lua_str(group))
        for it in rows:
            out.append(entry_line(it, set_of, extra_for(it) if extra_for else ""))
        out.append("    },")
    out.append("}")
    out.append("")
    out.append("%s_ORDER = { %s }" % (varname, ", ".join(lua_str(o) for o in order)))
    out.append("")
    io.open(path, "w", encoding="utf-8", newline=chr(10)).write(chr(10).join(out))
    return sum(len(v) for v in groups.values()), len(order)


def main():
    loot = json.loads(io.open(os.path.join(DATA, "dungeon-loot.json"), encoding="utf-8").read())
    weights = json.loads(io.open(os.path.join(DATA, "stat-weights.json"), encoding="utf-8").read())

    # Set membership, if it has been collected. Optional on purpose: the
    # emitter must still run on a checkout that has not scraped sets yet.
    sets_path = os.path.join(DATA, "item-sets.json")
    set_of = {}
    if os.path.exists(sets_path):
        set_of = json.loads(io.open(sets_path, encoding="utf-8").read()).get("index") or {}

    out = [
        "-- Wick's Gear",
        "-- Data.lua: generated by WickSuite/tools/emit-gear-data.py on %s." % time.strftime("%Y-%m-%d"),
        "-- Do not edit. Re-run the scrapers and then this.",
        "--",
        "-- Item ids, where they come from, and a name and stat line to fall",
        "-- back on. The client is asked first and its answer always wins,",
        "-- because it is the one this server is using. But on the Forever",
        "-- beta the client cannot name an item the character has never",
        "-- encountered: of thirteen things in Gnomeregan it knew three. An",
        "-- addon that shows you a list of blanks is not worth shipping, so",
        "-- these are here for when it has nothing.",
        "",
        "local ADDON, ns = ...",
        "",
        "ns.SOURCE = %s" % lua_str(loot.get("source", "")),
        "ns.COLLECTED = %s" % lua_str(loot.get("statsCollected") or loot.get("collected")),
        "",
        "-- dungeon -> { levels, items = { entry } }, where an entry is",
        "--   id, req, how, from, name, q, slot, stats",
        "--   ilvl      item level, for sorting and for comparing like with like",
        "--   set       the set it belongs to, when it belongs to one",
        "--   cls, sub  item class and subclass, which is how a one-hander is",
        "--             told from a two-hander and cloth from plate",
        "--   dps, spd  weapons only",
        "--",
        "-- how is \"drop\" or \"quest\"; from is the boss or quest giver. The",
        "-- name, quality, slot and stats are what a tooltip is built from when",
        "-- the client has never seen the item and cannot describe it.",
        "ns.DUNGEONS = {",
    ]

    order = []
    for name, d in loot["dungeons"].items():
        rows = []
        for bucket, how in (("drops", "drop"), ("questRewards", "quest")):
            for it in d.get(bucket, []):
                if not it.get("id"):
                    continue
                frm = (it.get("droppedBy") or [None])[0]
                st = it.get("stats") or {}
                keep = {"strength": "str", "agility": "agi", "stamina": "sta",
                        "intellect": "int", "spirit": "spi", "armor": "armor"}
                bits = ["%s = %d" % (short, st[long])
                        for long, short in keep.items()
                        if isinstance(st.get(long), int)]
                extra = ""
                if isinstance(it.get("ilvl"), int):
                    extra += ", ilvl = %d" % it["ilvl"]
                setname = set_of.get(str(it["id"]))
                if setname:
                    extra += ", set = " + lua_str(setname)
                if isinstance(it.get("itemClass"), int):
                    extra += ", cls = %d" % it["itemClass"]
                if isinstance(it.get("itemSubclass"), int):
                    extra += ", sub = %d" % it["itemSubclass"]
                # Weapons only, and only when the scrape actually got them.
                if isinstance(it.get("dps"), (int, float)) and it["dps"]:
                    extra += ", dps = %.1f" % it["dps"]
                if isinstance(it.get("speed"), (int, float)) and it["speed"]:
                    extra += ", spd = %.2f" % it["speed"]
                rows.append(
                    "        { id = %d, req = %d, how = %s%s, name = %s, q = %s%s%s%s }," % (
                        it["id"], it.get("reqLevel") or 0, lua_str(how),
                        (", from = " + lua_str(frm)) if frm else "",
                        lua_str(it.get("name") or ""),
                        lua_str(it.get("quality") or "common"),
                        (", slot = " + lua_str(it["slot"])) if it.get("slot") else "",
                        (", stats = { " + ", ".join(bits) + " }") if bits else "",
                        extra))
        if not rows:
            continue
        order.append(name)
        out.append("    [%s] = {" % lua_str(name))
        out.append("        levels = %s," % lua_str(d.get("levels", "")))
        if d.get("levelsDerived"):
            # Wowhead publishes no range for this one, so the range is
            # what its loot asks for. Say so rather than implying it is
            # the dungeon's own bracket.
            out.append("        levelsDerived = true,")
        out.append("        zone = %d," % d.get("zoneId", 0))
        out.append("        items = {")
        out.extend("    " + r for r in rows)
        out.append("        },")
        out.append("    },")
    out.append("}")
    out.append("")
    out.append("-- In the order you would actually run them.")
    out.append("ns.DUNGEON_ORDER = { %s }" % ", ".join(lua_str(n) for n in order))
    out.append("")

    # Weights. Small enough to inline, and the addon needs them to score.
    out.append("-- Per point, scaled so the class's primary stat is 1.0.")
    out.append("ns.WEIGHTS = {")
    for key, w in weights["weights"].items():
        bits = ["%s = %g" % (k, v) for k, v in w.items() if not k.startswith("_")]
        out.append("    [%s] = { %s }," % (lua_str(key), ", ".join(bits)))
    out.append("}")
    out.append("")
    out.append("ns.DPS_RATE = { %s }" % ", ".join(
        "%s = %g" % (k, v) for k, v in weights["weapons"]["dpsPerPrimaryPoint"].items()))
    out.append("")
    out.append("-- What each class may wear or wield, by item class and subclass.")
    out.append("-- A negative armour subclass is a cloak, ring, neck or trinket,")
    out.append("-- which carries no restriction at all. armorAt is the level a")
    out.append("-- class is trained in that armour type, for mail and plate at 40.")
    out.append("ns.PROFICIENCY = {")
    for key, p in weights["proficiency"].items():
        if key.startswith("_"):
            continue
        at = p.get("armorAt") or {}
        at_lua = ", ".join("[%s] = %d" % (sub, lvl) for sub, lvl in sorted(at.items()))
        out.append("    [%s] = { armor = { %s }, weapon = { %s }%s }," % (
            lua_str(key),
            ", ".join(str(n) for n in p["armor"]),
            ", ".join(str(n) for n in p["weapon"]),
            (", armorAt = { " + at_lua + " }") if at_lua else ""))
    out.append("}")
    out.append("")

    os.makedirs(ADDON, exist_ok=True)
    path = os.path.join(ADDON, "Data.lua")
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    items = sum(len(d.get("drops", [])) + len(d.get("questRewards", []))
                for d in loot["dungeons"].values())
    print("Wrote %s" % path)
    print("  %d dungeons, %d items, %d classes weighted" % (
        len(order), items, len([k for k in weights["weights"]])))
    print("  %.1f KB" % (os.path.getsize(path) / 1024.0))

    # ---- Crafted, grouped by profession -----------------------------
    crafted_path = os.path.join(DATA, "crafted.json")
    if os.path.exists(crafted_path):
        craft = json.loads(io.open(crafted_path, encoding="utf-8").read())
        groups = {}
        for prof, made in (craft.get("professions") or {}).items():
            rows = [m for m in made if m.get("gear")]
            if rows:
                groups[prof.capitalize()] = rows
        head = [
            "-- Wick's Gear",
            "-- DataCrafted.lua: generated by WickSuite/tools/emit-gear-data.py on %s."
            % time.strftime("%Y-%m-%d"),
            "-- Do not edit. Re-run the scrapers and then this.",
            "--",
            "-- What the four gear professions make, grouped by profession, with",
            "-- the skill each recipe is learned at. Reagents are deliberately",
            "-- absent: naming them needs a second scrape and a shopping list is",
            "-- not what this list is for.",
            "",
            "local ADDON, ns = ...",
            "if not WickCore then return end   -- said once in Core.lua",
            "",
        ]
        n, g = emit_table(os.path.join(ADDON, "DataCrafted.lua"), head, "ns.CRAFTED",
                          groups, set_of,
                          extra_for=lambda it: ("skill = %d" % it["skill"])
                          if isinstance(it.get("skill"), int) else "")
        print("  crafted: %d items across %d professions" % (n, g))

    # ---- Set bonuses -------------------------------------------------
    bonus_path = os.path.join(DATA, "set-bonuses.json")
    if os.path.exists(bonus_path):
        bon = json.loads(io.open(bonus_path, encoding="utf-8").read())
        out2 = [
            "-- Wick's Gear",
            "-- DataSetBonus.lua: generated by WickSuite/tools/emit-gear-data.py on %s."
            % time.strftime("%Y-%m-%d"),
            "-- Do not edit. Re-run the scrapers and then this.",
            "--",
            "-- Classic's set bonuses, not Forever's. Forever publishes none:",
            "-- its set tooltip carries the name and nothing else. These are the",
            "-- same sets carried forward, so Classic is the best source there",
            "-- is, but Forever has retuned things Classic had before, so the",
            "-- addon shows them as a guide and says where they came from.",
            "",
            "local ADDON, ns = ...",
            "if not WickCore then return end   -- said once in Core.lua",
            "",
            "ns.SET_BONUS_APPROXIMATE = true",
            "ns.SET_BONUS = {",
        ]
        n = 0
        for name in sorted(bon.get("sets") or {}):
            rows = bon["sets"][name]["bonuses"]
            out2.append("    [%s] = {" % lua_str(name))
            for b in rows:
                out2.append("        { pieces = %d, text = %s }," % (
                    b["pieces"], lua_str(b["text"])))
                n += 1
            out2.append("    },")
        out2.append("}")
        out2.append("")
        io.open(os.path.join(ADDON, "DataSetBonus.lua"), "w",
                encoding="utf-8", newline="\n").write("\n".join(out2))
        print("  set bonuses: %d lines across %d sets" % (n, len(bon.get("sets") or {})))

    # ---- Quest rewards, grouped by zone ------------------------------
    quest_path = os.path.join(DATA, "quest-rewards.json")
    if os.path.exists(quest_path):
        quests = json.loads(io.open(quest_path, encoding="utf-8").read())
        groups = {z: d.get("rewards") or [] for z, d in (quests.get("zones") or {}).items()}
        head = [
            "-- Wick's Gear",
            "-- DataQuests.lua: generated by WickSuite/tools/emit-gear-data.py on %s."
            % time.strftime("%Y-%m-%d"),
            "-- Do not edit. Re-run the scrapers and then this.",
            "--",
            "-- Quest rewards worth crossing a zone for, grouped by zone. Blue",
            "-- and above only: a zone hands out dozens of greens and nobody",
            "-- plans a route around a green. Instance quest rewards are in",
            "-- Data.lua with the rest of that dungeon's loot.",
            "",
            "local ADDON, ns = ...",
            "if not WickCore then return end   -- said once in Core.lua",
            "",
        ]
        n, g = emit_table(os.path.join(ADDON, "DataQuests.lua"), head, "ns.QUESTS",
                          groups, set_of)
        print("  quest rewards: %d items across %d zones" % (n, g))


if __name__ == "__main__":
    main()
